### ISSUE TITLE
the error

### ISSUE THREAD

**Issue by dirablue** [numbofathma/phaser-typescript-webpack#1]
hi, when I run this project. error occurred

```
ERROR in xxxxx/phaser-typescript-webpack/src/prefabs/mushroom.ts
./src/prefabs/mushroom.ts
[tsl] ERROR in xxxxx/phaser-typescript-webpack/src/prefabs/mushroom.ts(16,14)
      TS2339: Property 'checkWorldBounds' does not exist on type 'Mushroom'.

ERROR in xxxxx/phaser-typescript-webpack/src/prefabs/mushroom.ts
./src/prefabs/mushroom.ts
[tsl] ERROR in xxxxx/phaser-typescript-webpack/src/prefabs/mushroom.ts(21,14)
      TS2339: Property 'angle' does not exist on type 'Mushroom'.
```

and It works when I commented out the code below in mushroom.ts 
```
// this.checkWorldBounds = true;
// this.angle += 1;
```

do you know the reason?

**Comment by numbofathma** [comment]
Did you change the Phaser version or smth? This boilerplate is just for the Phaser CE edition.

**Comment by dirablue** [comment]
hi @numbofathma 

no, I didn't change anything. I just cloned this project and ran it with following the description.
are there any middlewares related to this issue?

**Comment by numbofathma** [comment]
Hi @dirablue,

I had a stupid cache on my machine and I could get tot the bottom of this issue.
I solved all of the errors now it should work as a dream.

Waiting on your reply to close the ticket.

**Comment by dirablue** [comment]
hi @numbofathma 

Thank you for fixing it. it works now.

**Comment by numbofathma** [comment]
Hi @dirablue,

Thank you for letting me know.
Have fun and happy coding!
